"""create initial schema

Revision ID: 8c68e00886a4
Revises:
Create Date: 2026-08-21 11:17:20.429002

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c68e00886a4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('profile', sa.String(length=50), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column(
    'created_at',
    sa.DateTime(timezone=True),
    server_default=sa.text('now()'),
    nullable=False,
),
sa.Column(
    'updated_at',
    sa.DateTime(timezone=True),
    server_default=sa.text('now()'),
    nullable=False,
),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_requests'))
    )
    op.create_index(op.f('ix_access_requests_email'), 'access_requests', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_requests_email'), table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###
